name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc  

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_cran("urlchecker")'

      - name: Check urlchecker Installation
        run: |
          R -e 'if (!requireNamespace("urlchecker")) quit("no", 1)'

      - name: Check links
        run: |
          R -e 'urlchecker::url_check()'
